services:
  - type: web
    name: mt-santai-running-club
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
